MicrosoftDocs/vscodespaces

vs-online/quickstarts/browser.md

Note: This PR is targeting the live branch.
Master and live seem out of sync.

remove empty note

---

README.md
vs-online/how-to/browser.md
vs-online/overview/what-is-vsonline.md
vs-online/resources/feedback.md

Corrected some spelling and duplicate word.

Spelling Correction

---

vs-online/resources/faq.md

Moving changes from master to live branch to publish FAQ change

Added trusted repos FAQ (#279)

---

vs-online/reference/configuring.md
vs-online/resources/faq.md

Merging in changes from @edgonmsft on our new Docker support and configuration options

Updating Docker support documentation

---

vs-online/TOC.yml
vs-online/how-to/browser.md
vs-online/how-to/self-hosting-cli.md
vs-online/how-to/self-hosting-vscode.md
vs-online/how-to/vscode.md
vs-online/reference/vsonline-cli.md

* Update TOC to include repo reference page
* Adding self-hosted entries to TOC
* Updating TOC
* Updated TOC and edits to existing pages
* New doc files for self-hosted and CLI
* Updated TOC, self-hosted how-tos, and cli reference
* Edit title of the CLI HowTo
* Tiny edits
* FIxing warnings about broken links
* Addressing more broken link warnings
* Attempting to fix final link
* Fixing broken link
* Add updated installation instructions
* Update vsonline-cli.md
* General edits and restructuring
* Fixed link I broke.
* Updated Debian instructions, addressed PR comments
* Addressing nit and typo comments
* Update vs-online/reference/vsonline-cli.md
Co-Authored-By: John Keech <jokeech@microsoft.com>
* Update vs-online/how-to/browser.md
Co-Authored-By: John Keech <jokeech@microsoft.com>
* …

Self hosted additions to documentation (#386)

---

vs-online/reference/vsonline-cli.md

Updated generic Linux installation instructions

---

vs-online/how-to/self-hosting-cli.md

Documented registration in a different region plan issue

Added known issue

---

vs-online/how-to/browser.md
vs-online/how-to/vscode.md
vs-online/resources/faq.md

Also remove "Never suspend" option from docs

Update docs with new quotas

---

vs-online/how-to/browser.md
vs-online/how-to/vscode.md
vs-online/resources/faq.md

Also remove "Never suspend" option from docs

Update docs with new quotas (#412)

---

vs-online/resources/troubleshooting.md

Adding a section to Troubleshooting for partially supported browser

Adding partially supported browsers

---

.openpublishing.publish.config.json
.openpublishing.redirection.json
vs-online/TOC.yml
vs-online/index.md

Migration PR to turn docfx build engine to v3

Docfx v3 migration

---

vs-online/TOC.yml

As per @profexorgeek guidance, removing deeplinks in the TOC for our docs

Removing deeplinks in TOC

---

vs-online/TOC.yml

Corrected spelling (#427)

---

vs-online/resources/faq.md

Some tweaks to the FAQ page from Varun.

Update to FAQ from Varun

---

vs-online/reference/configuring-windows.md

Small update to correct/update some of the version numbers.

Updating version numbers

---

vs-online/reference/personalizing.md

Correct note block formatting on Personalizing page

---

vs-online/TOC.yml
vs-online/resources/disaster-recovery-guidance.md

Per Azure compliance requirements, adding customer enablement steps for disaster recovery.

Disaster recovery guidance

---

vs-online/how-to/browser.md
vs-online/how-to/self-hosting-cli.md
vs-online/how-to/self-hosting-vscode.md
vs-online/how-to/vscode.md
vs-online/how-to/vside.md
vs-online/quickstarts/browser.md
vs-online/quickstarts/vs.md
vs-online/quickstarts/vscode.md
vs-online/reference/configuring-windows.md
vs-online/reference/configuring.md
vs-online/reference/personalizing.md
vs-online/reference/repository.md
vs-online/reference/vsonline-cli.md
vs-online/resources/disaster-recovery-guidance.md
vs-online/resources/faq.md
vs-online/resources/feedback.md
vs-online/resources/troubleshooting.md

Update ms.topic to match contributor guide https://review.docs.microsoft.com/en-us/help/contribute/metadata-attributes?branch=master

Update topic types

---

vs-online/how-to/browser.md
vs-online/how-to/self-hosting-cli.md
vs-online/how-to/self-hosting-vscode.md
vs-online/how-to/vscode.md
vs-online/how-to/vside.md
vs-online/overview/what-is-vsonline.md
vs-online/quickstarts/browser.md
vs-online/quickstarts/vs.md
vs-online/quickstarts/vscode.md
vs-online/reference/configuring-windows.md
vs-online/reference/configuring.md
vs-online/reference/personalizing.md
vs-online/reference/repository.md
vs-online/reference/vsonline-cli.md
vs-online/resources/disaster-recovery-guidance.md
vs-online/resources/faq.md
vs-online/resources/feedback.md
vs-online/resources/troubleshooting.md

Changing topic metadatga from 
ms.service: visual-studio-online
to
ms.prod: visual-studio-family
ms.technology: visual-studio-codespaces
to align with current DevRel reporting for LiveShare and IntelliCode.

Update to ms.prod and ms.technology

---

scripts/InstallWSL2.ps1

I'm adding the PowerShell we're referencing in the Release Notes, to show an example of how to configure WSL2 in a Windows Codespace VM.

Adding the WSL2 configuration script example.

---

vs-online/reference/vsonline-cli.md

Added note for use as service as for example Alpine Linux is not supported

---

vscodespaces/quickstarts/vs.md

Using a more interesting repository for the quickstart.

Change acangialosi/tictactoe to eshoponweb

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/transition-support.md

Adding templates for bugs with the current service, feature requests, and transition help

Update issue templates
